services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: no
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server
    volumes: 
      - cache:/data 

  postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  cache:

